name: Python

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
        - "2.7"
        - "3.5"
        - "3.6"
        - "3.7"
        - "pypy3.6-7.0.0"
    env:
      PRESTO_VERSION: 0.202
  
    steps:
    - uses: actions/checkout@v2
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
    - run: sudo apt-get install -y libkrb5-dev
    - run: pip install .[tests]
    - run: pytest -s tests/ integration_tests/